<div class="challenge-instructions es6"><div><section id="description">
<p><code>catch</code> is the method used when your promise has been rejected. It is executed immediately after a promise's <code>reject</code> method is called. Hereâ€™s the syntax:</p>
<pre class="language-js"><code class="language-js">myPromise<span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token parameter">error</span> <span class="token operator">=&gt;</span> <span class="token punctuation">{</span>
  
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre>
<p><code>error</code> is the argument passed in to the <code>reject</code> method.</p>
</section></div><hr/><div><section id="instructions">
<p>Add the <code>catch</code> method to your promise. Use <code>error</code> as the parameter of its callback function and log <code>error</code> to the console.</p>
</section></div><hr/></div>